config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :plays, only: [:new, :create]
  resources :images, only: [:index, :create]

  root to: 'images#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  has_many_attached :images
end

app/models/play.rb
class Play < ApplicationRecord
  scope :desc_order, -> { order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
  end

  def create
    Image.create(images: params[:images])
    redirect_to root_path, flash: { success: "Images uploaded successfully" }
  end
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  def new
    @play = Play.new
    @plays = Play.desc_order

    prepare_hash
  end

  def create
    @play = Play.create(plays_params)
    @plays = Play.desc_order
  end

  private

  def plays_params
    params.require(:play).permit(:timer_value, :url)
  end

  def prepare_hash
    # sample method of array is used to get 10 random elements from the array
    urls = Image.last.images.map{|image| url_for(image)}.sample(10)

    @req_hash, count = [{}, 0]
    10.times do |index|
      count = 0 if urls[count].nil?
      @req_hash[index + 1] = urls[count]
      count += 1
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/index.html.erb
<hr>
<%= link_to "Play Game", new_play_path %>
<hr>
<br>

<%= form_with url: images_path, html: {multipart: true} do |f| %>
  <%= f.file_field :images, accept: 'image/png, image/gif, image/jpeg, image/jpg', multiple: true %>
  <%= f.submit 'Upload Picture' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/plays/_table_data.html.erb
<table style="width:100%">
  <tr>
    <th>Counter Value</th>
    <th>Image</th>
  </tr>
  <% plays.each do |play| %>
    <tr>
      <td><%= play.timer_value %></td>
      <td><img src="<%= play.url %>" id="image" height="200" width="250"></td>
    </tr>
  <% end %>
</table>

app/views/plays/create.js.erb
$('#table-data').html("<%= escape_javascript render(:partial => 'table_data', locals: { plays: @plays}) %>");

app/views/plays/new.html.erb
<h1>Counter: <span id='counter'></span></h1>

<%= form_with model: @play do |f| %>

  <%= f.hidden_field :timer_value, data: {"req-hash": @req_hash} %>
  <%= f.hidden_field :url %>

  <img src="" id="image" height="200" width="200">
  <br>
  <%= f.submit 'Submit' %>
<% end %>

<br>
<br>

<div id="table-data">
  <%= render partial: 'table_data', locals: { plays: @plays } %>
</div>